import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Logo } from "@/components/logo";
import { SidebarNavItem } from "@/templates/components/sidebar/navItem";
import { UserProfile } from "@/templates/components/userProfile";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <main className="grid grid-cols-[2fr_10fr]">
            <aside>
                <nav className="p-4 bg-white h-screen">
                    <ul className="flex flex-col space-y-3">
                      <SidebarNavItem link="/dashboard" name="Home" icon="material-symbols:home-rounded" active /> 
                      <SidebarNavItem link="/accounts" name="Accounts" icon="material-symbols:account-balance-rounded" />
                    </ul>
                </nav>
            </aside>
            <article className="">
              <header className="p-4 bg-white  flex justify-between items-center">
                  <Logo textClassName="text-xl font-bold" />
                  <UserProfile
                    name="John Doe"
                    imageUrl="https://i.pravatar.cc/80?img=12"
                  />
              </header>
              {children}            
            </article> 
        </main>
      </body>
    </html>
  );
}
