import type { Metadata } from "next";
import { Geist_Mono, Inter } from "next/font/google";
import "./globals.css";

import { auth } from "@/auth";
import { Appbar } from "@/components/appbar";
import { Header } from "@/templates/composites/header";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getHeaderUser() {
  const session = await auth();

  if (!session?.user) {
    return null;
  }

  return {
    name: `${session.user.firstName} ${session.user.lastName}`,
    avatarUrl: session.user.avatarUrl,
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerUser = await getHeaderUser();
  const bodyClassName = [
    `${inter.variable} ${geistMono.variable} h-full w-full antialiased`,
    headerUser ? "md:grid md:grid-cols-[200px_2fr] md:grid-rows-[auto_1fr]" : "",
  ].join(" ");

  return (
    <html
      lang="en"
      className={`${inter.variable} ${geistMono.variable} h-full w-full antialiased`}
    >
      <body className={`${bodyClassName} min-h-screen h-auto relative`}>
          {headerUser ? (
            <Header user={headerUser} notificationCount={3}/>
          ) : null}
        {headerUser ? (
          <Appbar className="md:col-start-1 md:row-start-1 md:row-span-2"/>
        ) : null}
        <main className={`bg-white gap-6 ${headerUser ? "pt-16 pb-16 md:col-start-2" : ""}`}>
          {children}
        </main>
      </body>
    </html>
  );
}
